### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by g-ongenae** [g-ongenae/fs-linter#3]
## Todo

- [ ]  Test
- [ ]  Doc for Rules and for code

## Feature for later

- [ ] Autocorrect
- [ ] Lint also:
	- [ ] gitmodules
	- [ ] link
- [ ] Add a config (rc) file
- [x] ignore files
- [ ] enable setting own colors style

## Rules

- [ ] type of file in respect naming conventions
	- [x] md in upper case
	- [x] js in camel case
	- [ ] py in snake case
- [ ] or more specific:
	- [x] camel case with first letter upercase only for module exporting class
	- [ ] test, etc. in specific folder
